POST http://localhost:8080/api/tutors
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ0cmFpblN5cyIsInN1YiI6IjUiLCJleHAiOjE3MTkzMzQ2MTAsImlhdCI6MTcxOTI0ODIxMH0.MWPkixEdCwA8ZYfCCEVQG2LOHMaDkAuEcU0EHKbjyhZ3Bs_Lcv556vKOqx4jA1uBibl7YpyWEoq6fuRdqBU_yqcaL3RQE8sVc7Wbv-py9Vznrefyk5VI0TaMLwy79qGLoHxg7k-TN0gIPwfmzr_k7vDVYKKXDLnNblkGX0bL6kd-A258gUGIlAoRxJAKNk_6HWXWl5_7eH6iNkuWwccflvyf2oIg9jITHeWiW0kX5tBpjoE21uPK6rAhQjIT_yEwoHtaG255iSResk_HPMIX9s6LgqegIyba6C65ZsnGgpsR64TWJchLU2ViiH84bJ8h5lQjcR0heqWzsup7WmRpMw

{
  "name": "André",
  "email": "andré@tutor.senai",
  "date_birth": "1900-01-01",
  "cpf": "222.222.222.22",
  "contact": "+55 657-435-45"
}

###