POST http://localhost:8080/api/exercises
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ0cmFpblN5cyIsInN1YiI6IjUiLCJleHAiOjE3MTkzNDIyNTQsImlhdCI6MTcxOTI1NTg1NH0.JCACgBDtbbFdwBBA0A28QYdlGuwmsvCQsQ6jjmThJdq_ThBIUkVn3a7-PfhkehZmMJl6YVtHTbTWypQtuXplqQ3RefXWM0EHsG8Rutp-7IGMU7N8EOYN1KvQigxQhWfTO6e936WvudIvpVsYxhWxvWjS357AntrcNYKQ7c2faqXMZAGluHJzEL7QQh6PfsZS_-UZQuxKQ_GtNrNoE5bkQ_oL8MlikyMOHuC5uoK1q-x08rCA7HJ1ca5ZTlfkNSKkxIDhO7782mtmXdwjn5SwutIs4is0TBo3U_d2eOC0dRgB9dZCu1B_iG5SySvvLtFnVQ2gzbdDLQ6oiRRTTe6uaw

{
  "description": "Levantamento Peso"
}

###

GET http://localhost:8080/api/exercises
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ0cmFpblN5cyIsInN1YiI6IjUiLCJleHAiOjE3MTkzNDIyNTQsImlhdCI6MTcxOTI1NTg1NH0.JCACgBDtbbFdwBBA0A28QYdlGuwmsvCQsQ6jjmThJdq_ThBIUkVn3a7-PfhkehZmMJl6YVtHTbTWypQtuXplqQ3RefXWM0EHsG8Rutp-7IGMU7N8EOYN1KvQigxQhWfTO6e936WvudIvpVsYxhWxvWjS357AntrcNYKQ7c2faqXMZAGluHJzEL7QQh6PfsZS_-UZQuxKQ_GtNrNoE5bkQ_oL8MlikyMOHuC5uoK1q-x08rCA7HJ1ca5ZTlfkNSKkxIDhO7782mtmXdwjn5SwutIs4is0TBo3U_d2eOC0dRgB9dZCu1B_iG5SySvvLtFnVQ2gzbdDLQ6oiRRTTe6uaw

###

GET http://localhost:8080/api/exercises/3
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ0cmFpblN5cyIsInN1YiI6IjUiLCJleHAiOjE3MTkzNDIyNTQsImlhdCI6MTcxOTI1NTg1NH0.JCACgBDtbbFdwBBA0A28QYdlGuwmsvCQsQ6jjmThJdq_ThBIUkVn3a7-PfhkehZmMJl6YVtHTbTWypQtuXplqQ3RefXWM0EHsG8Rutp-7IGMU7N8EOYN1KvQigxQhWfTO6e936WvudIvpVsYxhWxvWjS357AntrcNYKQ7c2faqXMZAGluHJzEL7QQh6PfsZS_-UZQuxKQ_GtNrNoE5bkQ_oL8MlikyMOHuC5uoK1q-x08rCA7HJ1ca5ZTlfkNSKkxIDhO7782mtmXdwjn5SwutIs4is0TBo3U_d2eOC0dRgB9dZCu1B_iG5SySvvLtFnVQ2gzbdDLQ6oiRRTTe6uaw

###

PUT http://localhost:8080/api/exercises/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ0cmFpblN5cyIsInN1YiI6IjUiLCJleHAiOjE3MTkzMzEyMjYsImlhdCI6MTcxOTI0NDgyNn0.WYfU20VBTX4fx6Zq4TM89Q8rh-rQ72STwJvCnw6ZkYyx5bVrWccSJ2FpYpseDrCsuPXRY7_PM9R03-ZVB0VI0tiDp3kuluFRdSTjYWXAfchf7HWEpfe2oCZ19rPX_FOPlFPlk6NyLQg99YzXRivi_hYFWy9CO-Nex03DYL9Bn3zCKsFnTePU4_RYCIcRv3lK93TrnHtt94C_8ZG2HVcOq3ET6C_DXEL7u1-j8e-d9GLMLmj4Cw6WVvozPCHdmOCcPscDE-Q60CgNUJca3rLMA6CQqW5JnIVfDPkTAzOX4Z-ciwPg-sH_bMMgFxXnGDiVXYfFVws_uaVLqhINr8XwdQ

{
  "description": "Pular"
}

###

DELETE http://localhost:8080/api/exercises/4
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ0cmFpblN5cyIsInN1YiI6IjUiLCJleHAiOjE3MTkzMzMzMzksImlhdCI6MTcxOTI0NjkzOX0.AT-mHjWv1SruuhFLF6SGecKLygl_0GD4weEAv97IMxeA51VcRBMu9vGYQoBlC5aGY9J5m449tPmB9HSd0_K_3IcfoJIdNQ61bL4A-eSmHNQ6oOIJyYqOKfWpa6Z1f07HBftKVzfSo0jba3hCWGFDNYNGLRJ4qyokqir_9YD1lFdvQ6gJnVR8feKLzwPo_7ONhOguVko7GZ2j0BKUz0zNjEVpWD5ADaljr_l_UQn64iGiFlmooT4UR2OmTx-MaUdVaCWYkTGW4dZAXYtiLt0GEb1CvJIZRcijazKA7mUKRRhbgaNGKKKGu_yaOXl2orD2g0mOVB2Gp7xO5oik_e3sNA

###
