POST http://localhost:8080/api/exercises
Content-Type: application/json
Authorization: Bearer

{
  "description": "Levantamento Peso"
}

###

GET http://localhost:8080/api/exercises
Authorization: Bearer

###

GET http://localhost:8080/api/exercises/3
Authorization: Bearer

###

PUT http://localhost:8080/api/exercises/1
Content-Type: application/json
Authorization: Bearer

{
  "description": "Pular"
}

###

DELETE http://localhost:8080/api/exercises/4
Authorization: Bearer

###
